import type {
  KPIData,
  ContratoMensual,
  ContratoPorTipo,
  Actividad,
  ComercialRanking,
  Comunicado,
  EmailStats,
  PuntoSuministro,
  CUPSBusquedaReciente,
  TarifaCompetidor,
  Material,
  Tutorial,
  Cliente,
  Oportunidad,
  CRMStats,
} from '@/lib/types'

export const mockKPIs: KPIData = {
  contratos_mes: 23,
  contratos_variacion: 15.4,
  potencia_total: 847.5,
  facturacion: 48320,
  tasa_conversion: 34.7,
  ranking: 3,
}

export const mockVentasMensuales: ContratoMensual[] = [
  { mes: 'Sep', contratos: 14, facturacion: 31200 },
  { mes: 'Oct', contratos: 18, facturacion: 38900 },
  { mes: 'Nov', contratos: 16, facturacion: 35100 },
  { mes: 'Dic', contratos: 12, facturacion: 28400 },
  { mes: 'Ene', contratos: 20, facturacion: 43500 },
  { mes: 'Feb', contratos: 23, facturacion: 48320 },
]

export const mockContratosPorTipo: ContratoPorTipo[] = [
  { tipo: 'Luz Hogar', actual: 9, anterior: 8 },
  { tipo: 'Luz Empresa', actual: 6, anterior: 4 },
  { tipo: 'Gas Hogar', actual: 5, anterior: 6 },
  { tipo: 'Gas Empresa', actual: 2, anterior: 1 },
  { tipo: 'Dual', actual: 1, anterior: 1 },
]

export const mockActividades: Actividad[] = [
  {
    id: '1',
    tipo: 'contrato',
    descripcion: 'Contrato firmado',
    cliente: 'Restaurante El Rincón, S.L.',
    fecha: '2026-02-21T10:30:00',
    importe: 3200,
  },
  {
    id: '2',
    tipo: 'visita',
    descripcion: 'Visita comercial realizada',
    cliente: 'Familia Martínez López',
    fecha: '2026-02-21T09:00:00',
  },
  {
    id: '3',
    tipo: 'contrato',
    descripcion: 'Contrato firmado',
    cliente: 'Talleres Hernández, S.A.',
    fecha: '2026-02-20T16:45:00',
    importe: 5800,
  },
  {
    id: '4',
    tipo: 'llamada',
    descripcion: 'Llamada de seguimiento',
    cliente: 'Peluquería Style & Cut',
    fecha: '2026-02-20T11:20:00',
  },
  {
    id: '5',
    tipo: 'email',
    descripcion: 'Propuesta enviada',
    cliente: 'Academia de Idiomas Berlín',
    fecha: '2026-02-19T14:00:00',
  },
  {
    id: '6',
    tipo: 'contrato',
    descripcion: 'Contrato firmado',
    cliente: 'García e Hijos Ferretería',
    fecha: '2026-02-19T10:15:00',
    importe: 2100,
  },
]

export const mockRanking: ComercialRanking[] = [
  { posicion: 1, nombre: 'Ana Rodríguez', contratos: 31, facturacion: 67400 },
  { posicion: 2, nombre: 'Miguel Fernández', contratos: 28, facturacion: 59200 },
  { posicion: 3, nombre: 'Carlos García', contratos: 23, facturacion: 48320 },
  { posicion: 4, nombre: 'Laura Sánchez', contratos: 19, facturacion: 41800 },
  { posicion: 5, nombre: 'David Torres', contratos: 16, facturacion: 34600 },
]

// ── CUPS ─────────────────────────────────────────────────────────────────────

export const mockCUPSDatabase: Record<string, PuntoSuministro> = {
  'ES0021000012345678AB': {
    cups: 'ES0021000012345678AB',
    tipo: 'electricidad',
    estado: 'activo',
    titular: 'Antonio Martínez López',
    nif: '12345678A',
    direccion: 'Calle Mayor, 14, 3º B',
    municipio: 'Madrid',
    provincia: 'Madrid',
    cp: '28001',
    comercializadora: 'Iberdrola Clientes S.A.U.',
    tarifa: '2.0TD',
    contador: 'telegestionado',
    potencias: [
      { periodo: 'P1', potencia: 3.45 },
      { periodo: 'P2', potencia: 3.45 },
    ],
    consumo_anual_kwh: 4820,
    consumo_mensual: [
      { mes: 'Mar', kwh: 340 }, { mes: 'Abr', kwh: 310 },
      { mes: 'May', kwh: 295 }, { mes: 'Jun', kwh: 380 },
      { mes: 'Jul', kwh: 510 }, { mes: 'Ago', kwh: 540 },
      { mes: 'Sep', kwh: 420 }, { mes: 'Oct', kwh: 360 },
      { mes: 'Nov', kwh: 390 }, { mes: 'Dic', kwh: 460 },
      { mes: 'Ene', kwh: 440 }, { mes: 'Feb', kwh: 375 },
    ],
    ultima_lectura: '2026-02-15',
    ahorro_estimado_anual: 186,
    tarifa_mega_recomendada: 'Hogar Inteligente 2.0TD',
    precios_mega: [
      { periodo: 'P1', precio: 0.128 },
      { periodo: 'P2', precio: 0.094 },
      { periodo: 'P3', precio: 0.062 },
    ],
  },
  'ES0031405000123456YZ': {
    cups: 'ES0031405000123456YZ',
    tipo: 'electricidad',
    estado: 'activo',
    titular: 'Talleres Hernández, S.A.',
    nif: 'A28123456',
    direccion: 'Polígono Industrial Norte, Nave 7',
    municipio: 'Alcalá de Henares',
    provincia: 'Madrid',
    cp: '28800',
    comercializadora: 'Endesa Energía S.A.U.',
    tarifa: '3.0TD',
    contador: 'telegestionado',
    potencias: [
      { periodo: 'P1', potencia: 45 },
      { periodo: 'P2', potencia: 45 },
      { periodo: 'P3', potencia: 45 },
      { periodo: 'P4', potencia: 45 },
      { periodo: 'P5', potencia: 45 },
      { periodo: 'P6', potencia: 45 },
    ],
    consumo_anual_kwh: 98400,
    consumo_mensual: [
      { mes: 'Mar', kwh: 7200 }, { mes: 'Abr', kwh: 7800 },
      { mes: 'May', kwh: 8100 }, { mes: 'Jun', kwh: 8900 },
      { mes: 'Jul', kwh: 9400 }, { mes: 'Ago', kwh: 7600 },
      { mes: 'Sep', kwh: 8200 }, { mes: 'Oct', kwh: 8500 },
      { mes: 'Nov', kwh: 8800 }, { mes: 'Dic', kwh: 9100 },
      { mes: 'Ene', kwh: 8700 }, { mes: 'Feb', kwh: 6100 },
    ],
    ultima_lectura: '2026-02-18',
    ahorro_estimado_anual: 2840,
    tarifa_mega_recomendada: 'Empresa Plus 3.0TD',
    precios_mega: [
      { periodo: 'P1', precio: 0.142 },
      { periodo: 'P2', precio: 0.098 },
      { periodo: 'P3', precio: 0.068 },
      { periodo: 'P4', precio: 0.058 },
      { periodo: 'P5', precio: 0.052 },
      { periodo: 'P6', precio: 0.048 },
    ],
  },
  'ES0980500000123456PQ': {
    cups: 'ES0980500000123456PQ',
    tipo: 'gas',
    estado: 'activo',
    titular: 'Restaurante El Rincón, S.L.',
    nif: 'B91234567',
    direccion: 'Calle Serrano, 52, Local',
    municipio: 'Madrid',
    provincia: 'Madrid',
    cp: '28006',
    comercializadora: 'Naturgy Iberia S.A.',
    tarifa: 'RL.2',
    contador: 'analógico',
    potencias: [
      { periodo: 'P1', potencia: 70 },
    ],
    consumo_anual_kwh: 52000,
    consumo_mensual: [
      { mes: 'Mar', kwh: 3200 }, { mes: 'Abr', kwh: 2900 },
      { mes: 'May', kwh: 2600 }, { mes: 'Jun', kwh: 2800 },
      { mes: 'Jul', kwh: 3100 }, { mes: 'Ago', kwh: 2400 },
      { mes: 'Sep', kwh: 3600 }, { mes: 'Oct', kwh: 4200 },
      { mes: 'Nov', kwh: 5100 }, { mes: 'Dic', kwh: 6200 },
      { mes: 'Ene', kwh: 6800 }, { mes: 'Feb', kwh: 5100 },
    ],
    ultima_lectura: '2026-02-10',
    ahorro_estimado_anual: 1240,
    tarifa_mega_recomendada: 'Gas Hostelería RL.2',
    precios_mega: [
      { periodo: 'P1', precio: 0.068 },
    ],
  },
}

export const mockCUPSRecientes: CUPSBusquedaReciente[] = [
  { cups: 'ES0031405000123456YZ', titular: 'Talleres Hernández, S.A.',  tipo: 'electricidad', fecha: '2026-02-21T10:30:00' },
  { cups: 'ES0021000012345678AB', titular: 'Antonio Martínez López',     tipo: 'electricidad', fecha: '2026-02-20T16:00:00' },
  { cups: 'ES0980500000123456PQ', titular: 'Restaurante El Rincón, S.L.', tipo: 'gas',          fecha: '2026-02-19T11:15:00' },
]

// ── Emails ──────────────────────────────────────────────────────────────────

export const mockEmailStats: EmailStats = {
  total_enviados: 148,
  tasa_apertura: 61.4,
  tasa_respuesta: 22.3,
  rebotados: 4,
}

export const mockComunicados: Comunicado[] = [
  {
    id: 'em-001',
    asunto: 'Propuesta tarifa Luz Empresa — Talleres Hernández, S.A.',
    tipo: 'propuesta',
    estado: 'respondido',
    destinatarios: [
      { nombre: 'José Hernández', email: 'jhernandez@talleres-hernandez.es', empresa: 'Talleres Hernández, S.A.' },
    ],
    fecha_envio: '2026-02-20T09:15:00',
    fecha_apertura: '2026-02-20T10:02:00',
    cuerpo: `Estimado José,\n\nMe pongo en contacto con usted para presentarle nuestra propuesta personalizada para Talleres Hernández, S.A.\n\nTras analizar su consumo actual, hemos diseñado una tarifa de Luz Empresa que le permitirá ahorrar hasta un 23% en su factura eléctrica mensual.\n\n**Detalles de la propuesta:**\n- Tarifa: Empresa Plus 3.0TD\n- Potencia contratada: 45 kW\n- Precio energía P1: 0,142 €/kWh\n- Precio energía P2: 0,098 €/kWh\n- Precio energía P3: 0,068 €/kWh\n- Permanencia: 12 meses\n\nAhorro estimado anual: 2.840 €\n\nQuedo a su disposición para cualquier consulta o para concretar una reunión.\n\nUn cordial saludo,\nCarlos García\nComercial MEGA ENERGÍA`,
    adjuntos: ['propuesta_talleres_hernandez_feb2026.pdf'],
  },
  {
    id: 'em-002',
    asunto: 'Seguimiento visita comercial — Restaurante El Rincón',
    tipo: 'seguimiento',
    estado: 'abierto',
    destinatarios: [
      { nombre: 'María López', email: 'info@restauranteelrincon.es', empresa: 'Restaurante El Rincón, S.L.' },
    ],
    fecha_envio: '2026-02-19T16:30:00',
    fecha_apertura: '2026-02-20T08:45:00',
    cuerpo: `Estimada María,\n\nFue un placer visitarles ayer en el restaurante. Como acordamos, le envío un resumen de los puntos tratados.\n\nTras revisar sus facturas de los últimos 6 meses, confirmamos que con nuestra tarifa Hostelería Dual (luz + gas) obtendría un ahorro significativo frente a su contrato actual.\n\n¿Podemos quedar esta semana para finalizar los detalles y proceder con la firma?\n\nQuedo pendiente de su respuesta.\n\nSaludos,\nCarlos García`,
    adjuntos: [],
  },
  {
    id: 'em-003',
    asunto: 'Bienvenido a MEGA ENERGÍA — Familia Martínez',
    tipo: 'bienvenida',
    estado: 'abierto',
    destinatarios: [
      { nombre: 'Antonio Martínez', email: 'amartinez@gmail.com' },
    ],
    fecha_envio: '2026-02-18T11:00:00',
    fecha_apertura: '2026-02-18T12:30:00',
    cuerpo: `Estimado Antonio,\n\nEs un placer darle la bienvenida a la familia MEGA ENERGÍA.\n\nSu contrato de Luz Hogar ya está activo y el suministro quedará operativo en los próximos 2-3 días hábiles. Le enviaremos una notificación en cuanto esté confirmado.\n\n**Sus datos de contrato:**\n- CUPS: ES0021000012345678AB\n- Tarifa: Hogar Inteligente 2.0TD\n- Potencia: 5,75 kW\n- Precio fijo mensual: 18,50 €\n\nPara cualquier consulta puede contactarme directamente en este email o llamarme al 612 345 678.\n\nGracias por confiar en nosotros.\n\nCarlos García\nComercial MEGA ENERGÍA`,
    adjuntos: ['contrato_martinez_lopez.pdf', 'guia_bienvenida_mega.pdf'],
  },
  {
    id: 'em-004',
    asunto: 'Propuesta renovación contrato — Academia de Idiomas Berlín',
    tipo: 'renovacion',
    estado: 'enviado',
    destinatarios: [
      { nombre: 'Sandra Weiss', email: 'direccion@academiaberlin.es', empresa: 'Academia de Idiomas Berlín, S.L.' },
      { nombre: 'Contabilidad', email: 'contabilidad@academiaberlin.es', empresa: 'Academia de Idiomas Berlín, S.L.' },
    ],
    fecha_envio: '2026-02-17T10:00:00',
    cuerpo: `Estimada Sandra,\n\nSu contrato actual con MEGA ENERGÍA vence el próximo 15 de marzo. Aprovecho para presentarle las condiciones mejoradas para la renovación.\n\nDada su trayectoria como cliente y su consumo, hemos preparado una oferta especial que incluye:\n\n- Precio energía P1 reducido: 0,128 €/kWh (antes 0,145 €/kWh)\n- Bono fidelidad: descuento del 5% durante 3 meses\n- Sin penalización por cambio de potencia\n\nPor favor, háganos saber si desea proceder con la renovación o si prefiere que le llame para explicarle los detalles.\n\nSaludos,\nCarlos García`,
    adjuntos: ['oferta_renovacion_academia_berlin_2026.pdf'],
  },
  {
    id: 'em-005',
    asunto: 'Novedades tarifarias febrero 2026 — MEGA ENERGÍA',
    tipo: 'informativo',
    estado: 'abierto',
    destinatarios: [
      { nombre: 'Pedro Ruiz', email: 'pedro.ruiz@ferreteria-garcia.es', empresa: 'García e Hijos Ferretería' },
      { nombre: 'Carmen Vega', email: 'cvega@peluqueria-stylecut.es', empresa: 'Peluquería Style & Cut' },
      { nombre: 'Luis Moreno', email: 'lmoreno@talleres-auto.es', empresa: 'Talleres Auto Moreno' },
    ],
    fecha_envio: '2026-02-15T09:00:00',
    fecha_apertura: '2026-02-15T14:22:00',
    cuerpo: `Estimados clientes,\n\nLes informamos de las novedades que MEGA ENERGÍA introduce este mes de febrero:\n\n**Nuevas tarifas:**\n- Tarifa Solar Plus: incluye gestión de excedentes de autoconsumo\n- Tarifa Nocturna Empresa: precio especial en horario valle (23h-7h)\n\n**Cambios regulatorios:**\nA partir del 1 de marzo, el Ministerio para la Transición Ecológica actualiza los peajes de red. Nuestras tarifas ya recogen estos cambios sin coste adicional para usted.\n\nPara más información, no dude en contactarme.\n\nUn saludo,\nCarlos García`,
    adjuntos: [],
  },
  {
    id: 'em-006',
    asunto: 'Oferta especial Dual Hogar — ahorra en luz Y gas',
    tipo: 'promocion',
    estado: 'rebotado',
    destinatarios: [
      { nombre: 'Ramón Pascual', email: 'rpascual@hotmail.comm' },
    ],
    fecha_envio: '2026-02-14T11:30:00',
    cuerpo: `Estimado Ramón,\n\nLe escribo para presentarle nuestra oferta exclusiva de este mes: el bono Dual Hogar.\n\nContratando luz y gas con MEGA ENERGÍA, obtendrá:\n- 10% de descuento en la factura de luz durante 6 meses\n- 8% de descuento en la factura de gas durante 6 meses\n- Gestión de los cambios de compañía sin ningún trámite por su parte\n\nEsta oferta es válida hasta el 28 de febrero.\n\n¿Le interesa? Con una llamada lo tenemos todo listo.\n\nSaludos,\nCarlos García`,
    adjuntos: [],
  },
  {
    id: 'em-007',
    asunto: 'Propuesta Luz Empresa — Clínica Dental Sonrisa',
    tipo: 'propuesta',
    estado: 'respondido',
    destinatarios: [
      { nombre: 'Dra. Elena Blanco', email: 'clinica@dentalsonrisa.es', empresa: 'Clínica Dental Sonrisa, S.L.' },
    ],
    fecha_envio: '2026-02-12T10:45:00',
    fecha_apertura: '2026-02-12T11:20:00',
    cuerpo: `Estimada Elena,\n\nAdjunto encontrará la propuesta que preparé tras nuestra reunión del pasado lunes.\n\nLa tarifa Empresa Sanitaria que le propongo está especialmente diseñada para centros médicos, con precio estable durante 24 meses y sin sorpresas en la factura.\n\nAhorro estimado respecto a su contrato actual: 1.680 € anuales.\n\nEspero su confirmación para proceder con el alta.\n\nSaludos,\nCarlos García`,
    adjuntos: ['propuesta_dental_sonrisa_feb2026.pdf'],
  },
  {
    id: 'em-008',
    asunto: 'Seguimiento propuesta — Gym FitPower',
    tipo: 'seguimiento',
    estado: 'enviado',
    destinatarios: [
      { nombre: 'Marcos Jiménez', email: 'info@gymfitpower.es', empresa: 'Gym FitPower S.L.' },
    ],
    fecha_envio: '2026-02-10T16:00:00',
    cuerpo: `Estimado Marcos,\n\nSigo pendiente de su respuesta sobre la propuesta que le envié el pasado día 3 de febrero.\n\nEntiendo que es una decisión importante, por eso quería recordarle que la oferta especial que incluía el descuento del 15% durante los primeros 3 meses vence el próximo viernes 14.\n\nSi tiene cualquier duda o quiere revisar algún punto de la propuesta, estoy disponible esta semana.\n\nSaludos,\nCarlos García`,
    adjuntos: [],
  },
]

// ── Comparador ────────────────────────────────────────────────────────────────────────────

export const tarifasComparador: TarifaCompetidor[] = [
  // MEGA ENERGÍA
  {
    id: 'mega-hogar-20td',
    comercializadora: 'MEGA ENERGÍA',
    nombre_tarifa: 'Hogar Inteligente 2.0TD',
    tipo: 'electricidad',
    precio_p1: 0.128, precio_p2: 0.094, precio_p3: 0.062,
    potencia_anual: 38.04, cuota_fija: 0, es_mega: true, destacado: true,
  },
  {
    id: 'mega-empresa-30td',
    comercializadora: 'MEGA ENERGÍA',
    nombre_tarifa: 'Empresa Plus 3.0TD',
    tipo: 'electricidad',
    precio_p1: 0.142, precio_p2: 0.098, precio_p3: 0.068,
    potencia_anual: 36.50, cuota_fija: 0, es_mega: true, destacado: true,
  },
  {
    id: 'mega-gas-rl2',
    comercializadora: 'MEGA ENERGÍA',
    nombre_tarifa: 'Gas Hogar RL.2',
    tipo: 'gas',
    precio_p1: 0.068,
    potencia_anual: 0, cuota_fija: 4.5, es_mega: true, destacado: true,
  },
  // Iberdrola
  {
    id: 'iberdrola-hogar',
    comercializadora: 'Iberdrola',
    nombre_tarifa: 'One Hogar 2.0TD',
    tipo: 'electricidad',
    precio_p1: 0.149, precio_p2: 0.112, precio_p3: 0.078,
    potencia_anual: 42.60, cuota_fija: 0, es_mega: false,
  },
  {
    id: 'iberdrola-empresa',
    comercializadora: 'Iberdrola',
    nombre_tarifa: 'One Empresa 3.0TD',
    tipo: 'electricidad',
    precio_p1: 0.158, precio_p2: 0.109, precio_p3: 0.074,
    potencia_anual: 39.80, cuota_fija: 0, es_mega: false,
  },
  // Endesa
  {
    id: 'endesa-hogar',
    comercializadora: 'Endesa',
    nombre_tarifa: 'One Luz 2.0TD',
    tipo: 'electricidad',
    precio_p1: 0.152, precio_p2: 0.108, precio_p3: 0.071,
    potencia_anual: 41.20, cuota_fija: 1.99, es_mega: false,
  },
  {
    id: 'endesa-empresa',
    comercializadora: 'Endesa',
    nombre_tarifa: 'Empresa Luz 3.0TD',
    tipo: 'electricidad',
    precio_p1: 0.161, precio_p2: 0.112, precio_p3: 0.076,
    potencia_anual: 40.10, cuota_fija: 0, es_mega: false,
  },
  // Naturgy
  {
    id: 'naturgy-hogar',
    comercializadora: 'Naturgy',
    nombre_tarifa: 'Luz Estable 2.0TD',
    tipo: 'electricidad',
    precio_p1: 0.145, precio_p2: 0.106, precio_p3: 0.069,
    potencia_anual: 43.80, cuota_fija: 2.50, es_mega: false,
  },
  {
    id: 'naturgy-gas',
    comercializadora: 'Naturgy',
    nombre_tarifa: 'Gas Natural Plus',
    tipo: 'gas',
    precio_p1: 0.079,
    potencia_anual: 0, cuota_fija: 5.8, es_mega: false,
  },
  // Repsol
  {
    id: 'repsol-hogar',
    comercializadora: 'Repsol',
    nombre_tarifa: 'Luz Premium 2.0TD',
    tipo: 'electricidad',
    precio_p1: 0.141, precio_p2: 0.103, precio_p3: 0.072,
    potencia_anual: 40.80, cuota_fija: 0, es_mega: false,
  },
  {
    id: 'repsol-gas',
    comercializadora: 'Repsol',
    nombre_tarifa: 'Gas Hogar',
    tipo: 'gas',
    precio_p1: 0.074,
    potencia_anual: 0, cuota_fija: 5.2, es_mega: false,
  },
]

// ── Materiales ────────────────────────────────────────────────────────────────

export const mockMateriales: Material[] = [
  {
    id: 'mat-001',
    titulo: 'Tarifas Luz Hogar — Febrero 2026',
    descripcion: 'Resumen de precios vigentes para la tarifa 2.0TD en hogares. Incluye comparativa con reguladas.',
    categoria: 'tarifas',
    formato: 'PDF',
    tamaño: '1.2 MB',
    fecha_actualizacion: '2026-02-01',
    descargas: 342,
    destacado: true,
    nuevo: true,
  },
  {
    id: 'mat-002',
    titulo: 'Tarifas Luz Empresa — Febrero 2026',
    descripcion: 'Precios para 3.0TD y 6.1TD. Periodos P1–P6 con tabla de potencias y discriminación horaria.',
    categoria: 'tarifas',
    formato: 'PDF',
    tamaño: '1.8 MB',
    fecha_actualizacion: '2026-02-01',
    descargas: 218,
    nuevo: true,
  },
  {
    id: 'mat-003',
    titulo: 'Tarifas Gas Hogar y Empresa — Q1 2026',
    descripcion: 'Precios RL.1, RL.2, RL.3 y descuentos por consumo. Incluye proyección trimestral.',
    categoria: 'tarifas',
    formato: 'PDF',
    tamaño: '0.9 MB',
    fecha_actualizacion: '2026-01-15',
    descargas: 176,
  },
  {
    id: 'mat-004',
    titulo: 'Contrato Luz Hogar — Modelo Oficial',
    descripcion: 'Modelo de contrato para suministro eléctrico en tarifa 2.0TD. Versión actualizada con CNMC 2026.',
    categoria: 'contratos',
    formato: 'DOCX',
    tamaño: '0.4 MB',
    fecha_actualizacion: '2026-01-10',
    descargas: 892,
    destacado: true,
  },
  {
    id: 'mat-005',
    titulo: 'Contrato Luz Empresa — Modelo Oficial',
    descripcion: 'Contrato para suministro eléctrico empresarial. Incluye anexo de potencias y garantías.',
    categoria: 'contratos',
    formato: 'DOCX',
    tamaño: '0.6 MB',
    fecha_actualizacion: '2026-01-10',
    descargas: 634,
  },
  {
    id: 'mat-006',
    titulo: 'Contrato Gas — Modelo Oficial',
    descripcion: 'Contrato para suministro de gas natural en todas las tarifas RL.',
    categoria: 'contratos',
    formato: 'DOCX',
    tamaño: '0.5 MB',
    fecha_actualizacion: '2026-01-10',
    descargas: 411,
  },
  {
    id: 'mat-007',
    titulo: 'Presentación Corporativa MEGA ENERGÍA',
    descripcion: 'Presentación de empresa para clientes: historia, valores, portfolio y ventajas competitivas.',
    categoria: 'presentaciones',
    formato: 'PPTX',
    tamaño: '8.4 MB',
    fecha_actualizacion: '2026-01-20',
    descargas: 289,
    destacado: true,
  },
  {
    id: 'mat-008',
    titulo: 'Deck Comercial — Propuesta Energía',
    descripcion: 'Plantilla de presentación para propuestas a clientes. Personalizable con nombre y datos.',
    categoria: 'presentaciones',
    formato: 'PPTX',
    tamaño: '5.1 MB',
    fecha_actualizacion: '2025-12-15',
    descargas: 512,
  },
  {
    id: 'mat-009',
    titulo: 'Formulario Solicitud Cambio de Comercializadora',
    descripcion: 'Formulario oficial para tramitar el cambio desde otra comercializadora a MEGA ENERGÍA.',
    categoria: 'formularios',
    formato: 'PDF',
    tamaño: '0.3 MB',
    fecha_actualizacion: '2026-01-05',
    descargas: 1243,
    destacado: true,
  },
  {
    id: 'mat-010',
    titulo: 'Formulario SEPA — Domiciliación Bancaria',
    descripcion: 'Mandato SEPA para autorizar el cobro de facturas. Válido para personas físicas y jurídicas.',
    categoria: 'formularios',
    formato: 'PDF',
    tamaño: '0.2 MB',
    fecha_actualizacion: '2025-11-01',
    descargas: 987,
  },
  {
    id: 'mat-011',
    titulo: 'Díptico Ahorro Energético — Hogar',
    descripcion: 'Material de marketing imprimible para entregar en visitas comerciales a particulares.',
    categoria: 'marketing',
    formato: 'PDF',
    tamaño: '3.2 MB',
    fecha_actualizacion: '2026-02-10',
    descargas: 423,
    nuevo: true,
  },
  {
    id: 'mat-012',
    titulo: 'Calculadora Ahorro — Excel',
    descripcion: 'Hoja de cálculo para calcular el ahorro estimado de un cliente según su consumo.',
    categoria: 'tarifas',
    formato: 'XLSX',
    tamaño: '0.7 MB',
    fecha_actualizacion: '2026-02-05',
    descargas: 678,
    destacado: true,
    nuevo: true,
  },
  {
    id: 'mat-013',
    titulo: 'Normativa Regulatoria — BOE Energía Q1 2026',
    descripcion: 'Resumen de cambios normativos del sector energético publicados en BOE en el primer trimestre.',
    categoria: 'normativa',
    formato: 'PDF',
    tamaño: '2.1 MB',
    fecha_actualizacion: '2026-01-31',
    descargas: 134,
  },
  {
    id: 'mat-014',
    titulo: 'Guía Autoconsumo Solar — Comercial',
    descripcion: 'Guía para explicar a clientes las opciones de autoconsumo y compensación de excedentes.',
    categoria: 'marketing',
    formato: 'PDF',
    tamaño: '4.6 MB',
    fecha_actualizacion: '2026-01-25',
    descargas: 256,
  },
]

// ── Tutoriales ────────────────────────────────────────────────────────────────

export const mockTutoriales: Tutorial[] = [
  {
    id: 'tut-001',
    titulo: 'Cómo presentar una propuesta comercial efectiva',
    descripcion: 'Aprende la metodología paso a paso para presentar propuestas que cierran. Incluye técnicas de manejo de objeciones y cierre.',
    categoria: 'ventas',
    formato: 'video',
    nivel: 'básico',
    duracion_min: 18,
    fecha_publicacion: '2026-02-10',
    autor: 'Equipo Formación MEGA',
    vistas: 1243,
    destacado: true,
    nuevo: true,
    tags: ['propuestas', 'cierre', 'objeciones'],
  },
  {
    id: 'tut-002',
    titulo: 'Entendiendo la factura de luz: guía para comerciales',
    descripcion: 'Desglosa cada componente de la factura eléctrica para explicarla con claridad a tus clientes.',
    categoria: 'tecnico',
    formato: 'articulo',
    nivel: 'básico',
    duracion_min: 12,
    fecha_publicacion: '2026-01-25',
    autor: 'Dpto. Técnico',
    vistas: 987,
    destacado: true,
    tags: ['factura', 'electricidad', 'explicación'],
  },
  {
    id: 'tut-003',
    titulo: 'Uso avanzado del Comparador de Tarifas',
    descripcion: 'Saca el máximo partido al comparador: escenarios dual, análisis de potencias y cómo generar una propuesta desde los resultados.',
    categoria: 'herramientas',
    formato: 'video',
    nivel: 'intermedio',
    duracion_min: 24,
    fecha_publicacion: '2026-02-05',
    autor: 'Equipo Producto',
    vistas: 654,
    nuevo: true,
    tags: ['comparador', 'tarifas', 'propuestas'],
  },
  {
    id: 'tut-004',
    titulo: 'Novedades regulatorias energéticas 2026',
    descripcion: 'Resumen de los cambios normativos que afectan a los comercializadores y qué debes saber para asesorar bien a tus clientes.',
    categoria: 'normativa',
    formato: 'webinar',
    nivel: 'intermedio',
    duracion_min: 45,
    fecha_publicacion: '2026-01-20',
    autor: 'Área Legal',
    vistas: 412,
    tags: ['normativa', 'BOE', 'regulación', '2026'],
  },
  {
    id: 'tut-005',
    titulo: 'Tarifa 3.0TD para empresas: todo lo que necesitas saber',
    descripcion: 'Guía completa sobre la tarifa 3.0TD: periodos, potencias, discriminación horaria y cómo argumentarla ante el cliente.',
    categoria: 'producto',
    formato: 'articulo',
    nivel: 'intermedio',
    duracion_min: 20,
    fecha_publicacion: '2026-01-15',
    autor: 'Dpto. Técnico',
    vistas: 789,
    destacado: true,
    tags: ['3.0TD', 'empresa', 'tarifa', 'potencia'],
  },
  {
    id: 'tut-006',
    titulo: 'Técnicas de prospección puerta a puerta',
    descripcion: 'Estrategias probadas para maximizar conversiones en visitas a hogares. Pitch inicial, rapport y manejo del no.',
    categoria: 'ventas',
    formato: 'video',
    nivel: 'básico',
    duracion_min: 22,
    fecha_publicacion: '2025-12-10',
    autor: 'Equipo Formación MEGA',
    vistas: 1876,
    tags: ['puerta a puerta', 'prospección', 'pitch'],
  },
  {
    id: 'tut-007',
    titulo: 'Cómo consultar e interpretar un CUPS',
    descripcion: 'Tutorial práctico sobre qué es el CUPS, dónde encontrarlo y qué información comercial puedes extraer de él.',
    categoria: 'herramientas',
    formato: 'video',
    nivel: 'básico',
    duracion_min: 10,
    fecha_publicacion: '2026-02-12',
    autor: 'Equipo Producto',
    vistas: 543,
    nuevo: true,
    tags: ['CUPS', 'suministro', 'datos'],
  },
  {
    id: 'tut-008',
    titulo: 'Autoconsumo solar: argumentario comercial',
    descripcion: 'Cómo explicar y vender el autoconsumo a clientes con tejado propio. ROI, subvenciones y excedentes.',
    categoria: 'producto',
    formato: 'webinar',
    nivel: 'avanzado',
    duracion_min: 60,
    fecha_publicacion: '2026-01-30',
    autor: 'Dpto. Solar MEGA',
    vistas: 328,
    tags: ['solar', 'autoconsumo', 'ROI', 'subvenciones'],
  },
  {
    id: 'tut-009',
    titulo: 'CRM WolfCRM: gestión de clientes y seguimiento',
    descripcion: 'Aprende a registrar visitas, crear oportunidades, hacer seguimiento y generar informes en WolfCRM.',
    categoria: 'herramientas',
    formato: 'video',
    nivel: 'básico',
    duracion_min: 35,
    fecha_publicacion: '2025-11-20',
    autor: 'Equipo Herramientas',
    vistas: 1102,
    destacado: true,
    tags: ['CRM', 'WolfCRM', 'seguimiento', 'clientes'],
  },
  {
    id: 'tut-010',
    titulo: 'Negociación avanzada con grandes cuentas',
    descripcion: 'Técnicas de negociación B2B para clientes empresariales: descuentos, condiciones especiales y gestión de decisores múltiples.',
    categoria: 'ventas',
    formato: 'webinar',
    nivel: 'avanzado',
    duracion_min: 50,
    fecha_publicacion: '2026-01-08',
    autor: 'Director Comercial',
    vistas: 445,
    tags: ['negociación', 'B2B', 'grandes cuentas'],
  },
]

// ── CRM ───────────────────────────────────────────────────────────────────────

export const mockCRMStats: CRMStats = {
  total_clientes: 47,
  clientes_activos: 31,
  prospectos: 12,
  oportunidades_abiertas: 8,
  valor_pipeline: 18400,
  conversiones_mes: 4,
}

export const mockClientes: Cliente[] = [
  {
    id: 'cli-001',
    nombre: 'Antonio Martínez López',
    email: 'amartinez@gmail.com',
    telefono: '612 345 678',
    tipo: 'hogar',
    estado: 'activo',
    comercializadora_actual: 'Iberdrola',
    cups_count: 1,
    contratos_mega: 1,
    ahorro_estimado: 186,
    fecha_alta: '2026-02-18',
    ultima_actividad: '2026-02-21T10:30:00',
    etiquetas: ['residencial'],
  },
  {
    id: 'cli-002',
    nombre: 'José Hernández',
    empresa: 'Talleres Hernández, S.A.',
    nif: 'A28123456',
    email: 'jhernandez@talleres-hernandez.es',
    telefono: '914 567 890',
    tipo: 'empresa',
    estado: 'activo',
    comercializadora_actual: 'Endesa',
    cups_count: 2,
    contratos_mega: 2,
    ahorro_estimado: 2840,
    fecha_alta: '2026-02-20',
    ultima_actividad: '2026-02-21T09:15:00',
    etiquetas: ['empresa', 'industrial'],
  },
  {
    id: 'cli-003',
    nombre: 'María López',
    empresa: 'Restaurante El Rincón, S.L.',
    nif: 'B91234567',
    email: 'info@restauranteelrincon.es',
    telefono: '915 678 901',
    tipo: 'empresa',
    estado: 'activo',
    comercializadora_actual: 'Naturgy',
    cups_count: 1,
    contratos_mega: 1,
    ahorro_estimado: 1240,
    fecha_alta: '2026-02-21',
    ultima_actividad: '2026-02-21T16:30:00',
    etiquetas: ['hostelería'],
  },
  {
    id: 'cli-004',
    nombre: 'Sandra Weiss',
    empresa: 'Academia de Idiomas Berlín, S.L.',
    nif: 'B87654321',
    email: 'direccion@academiaberlin.es',
    telefono: '916 789 012',
    tipo: 'empresa',
    estado: 'prospecto',
    comercializadora_actual: 'Repsol',
    cups_count: 1,
    contratos_mega: 0,
    ahorro_estimado: 820,
    ultima_actividad: '2026-02-17T10:00:00',
    etiquetas: ['formación'],
  },
  {
    id: 'cli-005',
    nombre: 'Carmen Vega',
    empresa: 'Peluquería Style & Cut',
    email: 'cvega@peluqueria-stylecut.es',
    telefono: '917 890 123',
    tipo: 'autonomo',
    estado: 'activo',
    comercializadora_actual: 'Iberdrola',
    cups_count: 1,
    contratos_mega: 1,
    ultima_actividad: '2026-02-15T14:22:00',
    etiquetas: ['comercio'],
  },
  {
    id: 'cli-006',
    nombre: 'Pedro Ruiz',
    empresa: 'García e Hijos Ferretería',
    email: 'pedro.ruiz@ferreteria-garcia.es',
    telefono: '918 901 234',
    tipo: 'empresa',
    estado: 'activo',
    comercializadora_actual: 'Endesa',
    cups_count: 1,
    contratos_mega: 1,
    fecha_alta: '2026-02-19',
    ultima_actividad: '2026-02-19T10:15:00',
    etiquetas: ['comercio'],
  },
  {
    id: 'cli-007',
    nombre: 'Dra. Elena Blanco',
    empresa: 'Clínica Dental Sonrisa, S.L.',
    email: 'clinica@dentalsonrisa.es',
    telefono: '919 012 345',
    tipo: 'empresa',
    estado: 'activo',
    comercializadora_actual: 'Naturgy',
    cups_count: 1,
    contratos_mega: 1,
    ahorro_estimado: 1680,
    fecha_alta: '2026-02-13',
    ultima_actividad: '2026-02-12T11:20:00',
    etiquetas: ['salud'],
  },
  {
    id: 'cli-008',
    nombre: 'Marcos Jiménez',
    empresa: 'Gym FitPower S.L.',
    email: 'info@gymfitpower.es',
    telefono: '920 123 456',
    tipo: 'empresa',
    estado: 'prospecto',
    comercializadora_actual: 'Iberdrola',
    cups_count: 0,
    contratos_mega: 0,
    ahorro_estimado: 3100,
    ultima_actividad: '2026-02-10T16:00:00',
    etiquetas: ['deporte'],
  },
  {
    id: 'cli-009',
    nombre: 'Ramón Pascual',
    email: 'rpascual@hotmail.com',
    telefono: '921 234 567',
    tipo: 'hogar',
    estado: 'inactivo',
    comercializadora_actual: 'Repsol',
    cups_count: 0,
    contratos_mega: 0,
    ultima_actividad: '2026-02-14T11:30:00',
  },
  {
    id: 'cli-010',
    nombre: 'Luis Moreno',
    empresa: 'Talleres Auto Moreno',
    email: 'lmoreno@talleres-auto.es',
    telefono: '922 345 678',
    tipo: 'empresa',
    estado: 'prospecto',
    comercializadora_actual: 'Endesa',
    cups_count: 0,
    contratos_mega: 0,
    ahorro_estimado: 2200,
    ultima_actividad: '2026-02-15T09:00:00',
    etiquetas: ['automoción'],
  },
]

export const mockOportunidades: Oportunidad[] = [
  {
    id: 'op-001',
    cliente_nombre: 'Marcos Jiménez',
    cliente_empresa: 'Gym FitPower S.L.',
    tipo_producto: 'luz_empresa',
    etapa: 'propuesta',
    prioridad: 'alta',
    valor_estimado: 3100,
    fecha_creacion: '2026-02-03',
    fecha_seguimiento: '2026-02-24',
    notas: 'Propuesta enviada el 3/2. Pendiente de respuesta. Descuento 15% primeros 3 meses incluido.',
  },
  {
    id: 'op-002',
    cliente_nombre: 'Sandra Weiss',
    cliente_empresa: 'Academia de Idiomas Berlín, S.L.',
    tipo_producto: 'luz_empresa',
    etapa: 'negociacion',
    prioridad: 'alta',
    valor_estimado: 820,
    fecha_creacion: '2026-02-10',
    fecha_seguimiento: '2026-02-22',
    notas: 'Contrato vence el 15/3. Oferta de renovación enviada con precio P1 reducido.',
  },
  {
    id: 'op-003',
    cliente_nombre: 'Luis Moreno',
    cliente_empresa: 'Talleres Auto Moreno',
    tipo_producto: 'dual',
    etapa: 'contactado',
    prioridad: 'media',
    valor_estimado: 2200,
    fecha_creacion: '2026-02-15',
    fecha_seguimiento: '2026-02-25',
    notas: 'Primer contacto por email. Interesado en tarifa dual. Pendiente visita.',
  },
  {
    id: 'op-004',
    cliente_nombre: 'Ramón Pascual',
    tipo_producto: 'dual',
    etapa: 'prospecto',
    prioridad: 'baja',
    valor_estimado: 480,
    fecha_creacion: '2026-02-14',
    notas: 'Email rebotado. Verificar contacto.',
  },
  {
    id: 'op-005',
    cliente_nombre: 'Antonio Martínez López',
    tipo_producto: 'gas_hogar',
    etapa: 'propuesta',
    prioridad: 'media',
    valor_estimado: 320,
    fecha_creacion: '2026-02-18',
    fecha_seguimiento: '2026-02-28',
    notas: 'Ya es cliente de luz. Ampliar con gas hogar.',
  },
  {
    id: 'op-006',
    cliente_nombre: 'José Hernández',
    cliente_empresa: 'Talleres Hernández, S.A.',
    tipo_producto: 'luz_empresa',
    etapa: 'ganado',
    prioridad: 'alta',
    valor_estimado: 5800,
    fecha_creacion: '2026-02-15',
    notas: 'Contrato firmado el 20/2.',
  },
  {
    id: 'op-007',
    cliente_nombre: 'Dra. Elena Blanco',
    cliente_empresa: 'Clínica Dental Sonrisa, S.L.',
    tipo_producto: 'luz_empresa',
    etapa: 'ganado',
    prioridad: 'media',
    valor_estimado: 1680,
    fecha_creacion: '2026-02-05',
    notas: 'Contrato firmado el 13/2.',
  },
  {
    id: 'op-008',
    cliente_nombre: 'Pedro Ruiz',
    cliente_empresa: 'García e Hijos Ferretería',
    tipo_producto: 'luz_empresa',
    etapa: 'ganado',
    prioridad: 'media',
    valor_estimado: 2100,
    fecha_creacion: '2026-02-12',
    notas: 'Contrato firmado el 19/2.',
  },
]
